#![allow(dead_code)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CountryInfo {
    pub code: &'static str,
    pub name: &'static str,
    pub bancho_id: u8,
    pub flag: &'static str,
}

pub const DEFAULT_COUNTRY_INFO: CountryInfo = CountryInfo {
    code: "VN",
    name: "Vietnam",
    bancho_id: 233,
    flag: "🇻🇳",
};

pub const COUNTRIES: &[CountryInfo] = &[
    CountryInfo { code: "OC", name: "OC", bancho_id: 1, flag: "🌐" },
    CountryInfo { code: "EU", name: "EU", bancho_id: 2, flag: "🌐" },
    CountryInfo { code: "AD", name: "AD", bancho_id: 3, flag: "🌐" },
    CountryInfo { code: "AE", name: "AE", bancho_id: 4, flag: "🌐" },
    CountryInfo { code: "AF", name: "AF", bancho_id: 5, flag: "🌐" },
    CountryInfo { code: "AG", name: "AG", bancho_id: 6, flag: "🌐" },
    CountryInfo { code: "AI", name: "AI", bancho_id: 7, flag: "🌐" },
    CountryInfo { code: "AL", name: "AL", bancho_id: 8, flag: "🌐" },
    CountryInfo { code: "AM", name: "AM", bancho_id: 9, flag: "🌐" },
    CountryInfo { code: "AN", name: "AN", bancho_id: 10, flag: "🌐" },
    CountryInfo { code: "AO", name: "AO", bancho_id: 11, flag: "🌐" },
    CountryInfo { code: "AQ", name: "AQ", bancho_id: 12, flag: "🌐" },
    CountryInfo { code: "AR", name: "AR", bancho_id: 13, flag: "🌐" },
    CountryInfo { code: "AS", name: "AS", bancho_id: 14, flag: "🌐" },
    CountryInfo { code: "AT", name: "AT", bancho_id: 15, flag: "🌐" },
    CountryInfo { code: "AU", name: "Australia", bancho_id: 16, flag: "🇦🇺" },
    CountryInfo { code: "AW", name: "AW", bancho_id: 17, flag: "🌐" },
    CountryInfo { code: "AZ", name: "AZ", bancho_id: 18, flag: "🌐" },
    CountryInfo { code: "BA", name: "BA", bancho_id: 19, flag: "🌐" },
    CountryInfo { code: "BB", name: "BB", bancho_id: 20, flag: "🌐" },
    CountryInfo { code: "BD", name: "BD", bancho_id: 21, flag: "🌐" },
    CountryInfo { code: "BE", name: "BE", bancho_id: 22, flag: "🌐" },
    CountryInfo { code: "BF", name: "BF", bancho_id: 23, flag: "🌐" },
    CountryInfo { code: "BG", name: "BG", bancho_id: 24, flag: "🌐" },
    CountryInfo { code: "BH", name: "BH", bancho_id: 25, flag: "🌐" },
    CountryInfo { code: "BI", name: "BI", bancho_id: 26, flag: "🌐" },
    CountryInfo { code: "BJ", name: "BJ", bancho_id: 27, flag: "🌐" },
    CountryInfo { code: "BM", name: "BM", bancho_id: 28, flag: "🌐" },
    CountryInfo { code: "BN", name: "BN", bancho_id: 29, flag: "🌐" },
    CountryInfo { code: "BO", name: "BO", bancho_id: 30, flag: "🌐" },
    CountryInfo { code: "BR", name: "Brazil", bancho_id: 31, flag: "🇧🇷" },
    CountryInfo { code: "BS", name: "BS", bancho_id: 32, flag: "🌐" },
    CountryInfo { code: "BT", name: "BT", bancho_id: 33, flag: "🌐" },
    CountryInfo { code: "BV", name: "BV", bancho_id: 34, flag: "🌐" },
    CountryInfo { code: "BW", name: "BW", bancho_id: 35, flag: "🌐" },
    CountryInfo { code: "BY", name: "BY", bancho_id: 36, flag: "🌐" },
    CountryInfo { code: "BZ", name: "BZ", bancho_id: 37, flag: "🌐" },
    CountryInfo { code: "CA", name: "Canada", bancho_id: 38, flag: "🇨🇦" },
    CountryInfo { code: "CC", name: "CC", bancho_id: 39, flag: "🌐" },
    CountryInfo { code: "CD", name: "CD", bancho_id: 40, flag: "🌐" },
    CountryInfo { code: "CF", name: "CF", bancho_id: 41, flag: "🌐" },
    CountryInfo { code: "CG", name: "CG", bancho_id: 42, flag: "🌐" },
    CountryInfo { code: "CH", name: "CH", bancho_id: 43, flag: "🌐" },
    CountryInfo { code: "CI", name: "CI", bancho_id: 44, flag: "🌐" },
    CountryInfo { code: "CK", name: "CK", bancho_id: 45, flag: "🌐" },
    CountryInfo { code: "CL", name: "CL", bancho_id: 46, flag: "🌐" },
    CountryInfo { code: "CM", name: "CM", bancho_id: 47, flag: "🌐" },
    CountryInfo { code: "CN", name: "China", bancho_id: 48, flag: "🇨🇳" },
    CountryInfo { code: "CO", name: "CO", bancho_id: 49, flag: "🌐" },
    CountryInfo { code: "CR", name: "CR", bancho_id: 50, flag: "🌐" },
    CountryInfo { code: "CU", name: "CU", bancho_id: 51, flag: "🌐" },
    CountryInfo { code: "CV", name: "CV", bancho_id: 52, flag: "🌐" },
    CountryInfo { code: "CX", name: "CX", bancho_id: 53, flag: "🌐" },
    CountryInfo { code: "CY", name: "CY", bancho_id: 54, flag: "🌐" },
    CountryInfo { code: "CZ", name: "CZ", bancho_id: 55, flag: "🌐" },
    CountryInfo { code: "DE", name: "Germany", bancho_id: 56, flag: "🇩🇪" },
    CountryInfo { code: "DJ", name: "DJ", bancho_id: 57, flag: "🌐" },
    CountryInfo { code: "DK", name: "DK", bancho_id: 58, flag: "🌐" },
    CountryInfo { code: "DM", name: "DM", bancho_id: 59, flag: "🌐" },
    CountryInfo { code: "DO", name: "DO", bancho_id: 60, flag: "🌐" },
    CountryInfo { code: "DZ", name: "DZ", bancho_id: 61, flag: "🌐" },
    CountryInfo { code: "EC", name: "EC", bancho_id: 62, flag: "🌐" },
    CountryInfo { code: "EE", name: "EE", bancho_id: 63, flag: "🌐" },
    CountryInfo { code: "EG", name: "EG", bancho_id: 64, flag: "🌐" },
    CountryInfo { code: "EH", name: "EH", bancho_id: 65, flag: "🌐" },
    CountryInfo { code: "ER", name: "ER", bancho_id: 66, flag: "🌐" },
    CountryInfo { code: "ES", name: "ES", bancho_id: 67, flag: "🌐" },
    CountryInfo { code: "ET", name: "ET", bancho_id: 68, flag: "🌐" },
    CountryInfo { code: "FI", name: "FI", bancho_id: 69, flag: "🌐" },
    CountryInfo { code: "FJ", name: "FJ", bancho_id: 70, flag: "🌐" },
    CountryInfo { code: "FK", name: "FK", bancho_id: 71, flag: "🌐" },
    CountryInfo { code: "FM", name: "FM", bancho_id: 72, flag: "🌐" },
    CountryInfo { code: "FO", name: "FO", bancho_id: 73, flag: "🌐" },
    CountryInfo { code: "FR", name: "France", bancho_id: 74, flag: "🇫🇷" },
    CountryInfo { code: "FX", name: "FX", bancho_id: 75, flag: "🌐" },
    CountryInfo { code: "GA", name: "GA", bancho_id: 76, flag: "🌐" },
    CountryInfo { code: "GB", name: "United Kingdom", bancho_id: 77, flag: "🇬🇧" },
    CountryInfo { code: "GD", name: "GD", bancho_id: 78, flag: "🌐" },
    CountryInfo { code: "GE", name: "GE", bancho_id: 79, flag: "🌐" },
    CountryInfo { code: "GF", name: "GF", bancho_id: 80, flag: "🌐" },
    CountryInfo { code: "GH", name: "GH", bancho_id: 81, flag: "🌐" },
    CountryInfo { code: "GI", name: "GI", bancho_id: 82, flag: "🌐" },
    CountryInfo { code: "GL", name: "GL", bancho_id: 83, flag: "🌐" },
    CountryInfo { code: "GM", name: "GM", bancho_id: 84, flag: "🌐" },
    CountryInfo { code: "GN", name: "GN", bancho_id: 85, flag: "🌐" },
    CountryInfo { code: "GP", name: "GP", bancho_id: 86, flag: "🌐" },
    CountryInfo { code: "GQ", name: "GQ", bancho_id: 87, flag: "🌐" },
    CountryInfo { code: "GR", name: "GR", bancho_id: 88, flag: "🌐" },
    CountryInfo { code: "GS", name: "GS", bancho_id: 89, flag: "🌐" },
    CountryInfo { code: "GT", name: "GT", bancho_id: 90, flag: "🌐" },
    CountryInfo { code: "GU", name: "GU", bancho_id: 91, flag: "🌐" },
    CountryInfo { code: "GW", name: "GW", bancho_id: 92, flag: "🌐" },
    CountryInfo { code: "GY", name: "GY", bancho_id: 93, flag: "🌐" },
    CountryInfo { code: "HK", name: "HK", bancho_id: 94, flag: "🌐" },
    CountryInfo { code: "HM", name: "HM", bancho_id: 95, flag: "🌐" },
    CountryInfo { code: "HN", name: "HN", bancho_id: 96, flag: "🌐" },
    CountryInfo { code: "HR", name: "HR", bancho_id: 97, flag: "🌐" },
    CountryInfo { code: "HT", name: "HT", bancho_id: 98, flag: "🌐" },
    CountryInfo { code: "HU", name: "HU", bancho_id: 99, flag: "🌐" },
    CountryInfo { code: "ID", name: "Indonesia", bancho_id: 100, flag: "🇮🇩" },
    CountryInfo { code: "IE", name: "IE", bancho_id: 101, flag: "🌐" },
    CountryInfo { code: "IL", name: "IL", bancho_id: 102, flag: "🌐" },
    CountryInfo { code: "IN", name: "IN", bancho_id: 103, flag: "🌐" },
    CountryInfo { code: "IO", name: "IO", bancho_id: 104, flag: "🌐" },
    CountryInfo { code: "IQ", name: "IQ", bancho_id: 105, flag: "🌐" },
    CountryInfo { code: "IR", name: "IR", bancho_id: 106, flag: "🌐" },
    CountryInfo { code: "IS", name: "IS", bancho_id: 107, flag: "🌐" },
    CountryInfo { code: "IT", name: "IT", bancho_id: 108, flag: "🌐" },
    CountryInfo { code: "JM", name: "JM", bancho_id: 109, flag: "🌐" },
    CountryInfo { code: "JO", name: "JO", bancho_id: 110, flag: "🌐" },
    CountryInfo { code: "JP", name: "Japan", bancho_id: 111, flag: "🇯🇵" },
    CountryInfo { code: "KE", name: "KE", bancho_id: 112, flag: "🌐" },
    CountryInfo { code: "KG", name: "KG", bancho_id: 113, flag: "🌐" },
    CountryInfo { code: "KH", name: "KH", bancho_id: 114, flag: "🌐" },
    CountryInfo { code: "KI", name: "KI", bancho_id: 115, flag: "🌐" },
    CountryInfo { code: "KM", name: "KM", bancho_id: 116, flag: "🌐" },
    CountryInfo { code: "KN", name: "KN", bancho_id: 117, flag: "🌐" },
    CountryInfo { code: "KP", name: "KP", bancho_id: 118, flag: "🌐" },
    CountryInfo { code: "KR", name: "South Korea", bancho_id: 119, flag: "🇰🇷" },
    CountryInfo { code: "KW", name: "KW", bancho_id: 120, flag: "🌐" },
    CountryInfo { code: "KY", name: "KY", bancho_id: 121, flag: "🌐" },
    CountryInfo { code: "KZ", name: "KZ", bancho_id: 122, flag: "🌐" },
    CountryInfo { code: "LA", name: "LA", bancho_id: 123, flag: "🌐" },
    CountryInfo { code: "LB", name: "LB", bancho_id: 124, flag: "🌐" },
    CountryInfo { code: "LC", name: "LC", bancho_id: 125, flag: "🌐" },
    CountryInfo { code: "LI", name: "LI", bancho_id: 126, flag: "🌐" },
    CountryInfo { code: "LK", name: "LK", bancho_id: 127, flag: "🌐" },
    CountryInfo { code: "LR", name: "LR", bancho_id: 128, flag: "🌐" },
    CountryInfo { code: "LS", name: "LS", bancho_id: 129, flag: "🌐" },
    CountryInfo { code: "LT", name: "LT", bancho_id: 130, flag: "🌐" },
    CountryInfo { code: "LU", name: "LU", bancho_id: 131, flag: "🌐" },
    CountryInfo { code: "LV", name: "LV", bancho_id: 132, flag: "🌐" },
    CountryInfo { code: "LY", name: "LY", bancho_id: 133, flag: "🌐" },
    CountryInfo { code: "MA", name: "MA", bancho_id: 134, flag: "🌐" },
    CountryInfo { code: "MC", name: "MC", bancho_id: 135, flag: "🌐" },
    CountryInfo { code: "MD", name: "MD", bancho_id: 136, flag: "🌐" },
    CountryInfo { code: "MG", name: "MG", bancho_id: 137, flag: "🌐" },
    CountryInfo { code: "MH", name: "MH", bancho_id: 138, flag: "🌐" },
    CountryInfo { code: "MK", name: "MK", bancho_id: 139, flag: "🌐" },
    CountryInfo { code: "ML", name: "ML", bancho_id: 140, flag: "🌐" },
    CountryInfo { code: "MM", name: "MM", bancho_id: 141, flag: "🌐" },
    CountryInfo { code: "MN", name: "MN", bancho_id: 142, flag: "🌐" },
    CountryInfo { code: "MO", name: "MO", bancho_id: 143, flag: "🌐" },
    CountryInfo { code: "MP", name: "MP", bancho_id: 144, flag: "🌐" },
    CountryInfo { code: "MQ", name: "MQ", bancho_id: 145, flag: "🌐" },
    CountryInfo { code: "MR", name: "MR", bancho_id: 146, flag: "🌐" },
    CountryInfo { code: "MS", name: "MS", bancho_id: 147, flag: "🌐" },
    CountryInfo { code: "MT", name: "MT", bancho_id: 148, flag: "🌐" },
    CountryInfo { code: "MU", name: "MU", bancho_id: 149, flag: "🌐" },
    CountryInfo { code: "MV", name: "MV", bancho_id: 150, flag: "🌐" },
    CountryInfo { code: "MW", name: "MW", bancho_id: 151, flag: "🌐" },
    CountryInfo { code: "MX", name: "MX", bancho_id: 152, flag: "🌐" },
    CountryInfo { code: "MY", name: "Malaysia", bancho_id: 153, flag: "🇲🇾" },
    CountryInfo { code: "MZ", name: "MZ", bancho_id: 154, flag: "🌐" },
    CountryInfo { code: "NA", name: "NA", bancho_id: 155, flag: "🌐" },
    CountryInfo { code: "NC", name: "NC", bancho_id: 156, flag: "🌐" },
    CountryInfo { code: "NE", name: "NE", bancho_id: 157, flag: "🌐" },
    CountryInfo { code: "NF", name: "NF", bancho_id: 158, flag: "🌐" },
    CountryInfo { code: "NG", name: "NG", bancho_id: 159, flag: "🌐" },
    CountryInfo { code: "NI", name: "NI", bancho_id: 160, flag: "🌐" },
    CountryInfo { code: "NL", name: "NL", bancho_id: 161, flag: "🌐" },
    CountryInfo { code: "NO", name: "NO", bancho_id: 162, flag: "🌐" },
    CountryInfo { code: "NP", name: "NP", bancho_id: 163, flag: "🌐" },
    CountryInfo { code: "NR", name: "NR", bancho_id: 164, flag: "🌐" },
    CountryInfo { code: "NU", name: "NU", bancho_id: 165, flag: "🌐" },
    CountryInfo { code: "NZ", name: "NZ", bancho_id: 166, flag: "🌐" },
    CountryInfo { code: "OM", name: "OM", bancho_id: 167, flag: "🌐" },
    CountryInfo { code: "PA", name: "PA", bancho_id: 168, flag: "🌐" },
    CountryInfo { code: "PE", name: "PE", bancho_id: 169, flag: "🌐" },
    CountryInfo { code: "PF", name: "PF", bancho_id: 170, flag: "🌐" },
    CountryInfo { code: "PG", name: "PG", bancho_id: 171, flag: "🌐" },
    CountryInfo { code: "PH", name: "Philippines", bancho_id: 172, flag: "🇵🇭" },
    CountryInfo { code: "PK", name: "PK", bancho_id: 173, flag: "🌐" },
    CountryInfo { code: "PL", name: "Poland", bancho_id: 174, flag: "🇵🇱" },
    CountryInfo { code: "PM", name: "PM", bancho_id: 175, flag: "🌐" },
    CountryInfo { code: "PN", name: "PN", bancho_id: 176, flag: "🌐" },
    CountryInfo { code: "PR", name: "PR", bancho_id: 177, flag: "🌐" },
    CountryInfo { code: "PS", name: "PS", bancho_id: 178, flag: "🌐" },
    CountryInfo { code: "PT", name: "PT", bancho_id: 179, flag: "🌐" },
    CountryInfo { code: "PW", name: "PW", bancho_id: 180, flag: "🌐" },
    CountryInfo { code: "PY", name: "PY", bancho_id: 181, flag: "🌐" },
    CountryInfo { code: "QA", name: "QA", bancho_id: 182, flag: "🌐" },
    CountryInfo { code: "RE", name: "RE", bancho_id: 183, flag: "🌐" },
    CountryInfo { code: "RO", name: "RO", bancho_id: 184, flag: "🌐" },
    CountryInfo { code: "RU", name: "Russia", bancho_id: 185, flag: "🇷🇺" },
    CountryInfo { code: "RW", name: "RW", bancho_id: 186, flag: "🌐" },
    CountryInfo { code: "SA", name: "SA", bancho_id: 187, flag: "🌐" },
    CountryInfo { code: "SB", name: "SB", bancho_id: 188, flag: "🌐" },
    CountryInfo { code: "SC", name: "SC", bancho_id: 189, flag: "🌐" },
    CountryInfo { code: "SD", name: "SD", bancho_id: 190, flag: "🌐" },
    CountryInfo { code: "SE", name: "SE", bancho_id: 191, flag: "🌐" },
    CountryInfo { code: "SG", name: "Singapore", bancho_id: 192, flag: "🇸🇬" },
    CountryInfo { code: "SH", name: "SH", bancho_id: 193, flag: "🌐" },
    CountryInfo { code: "SI", name: "SI", bancho_id: 194, flag: "🌐" },
    CountryInfo { code: "SJ", name: "SJ", bancho_id: 195, flag: "🌐" },
    CountryInfo { code: "SK", name: "SK", bancho_id: 196, flag: "🌐" },
    CountryInfo { code: "SL", name: "SL", bancho_id: 197, flag: "🌐" },
    CountryInfo { code: "SM", name: "SM", bancho_id: 198, flag: "🌐" },
    CountryInfo { code: "SN", name: "SN", bancho_id: 199, flag: "🌐" },
    CountryInfo { code: "SO", name: "SO", bancho_id: 200, flag: "🌐" },
    CountryInfo { code: "SR", name: "SR", bancho_id: 201, flag: "🌐" },
    CountryInfo { code: "ST", name: "ST", bancho_id: 202, flag: "🌐" },
    CountryInfo { code: "SV", name: "SV", bancho_id: 203, flag: "🌐" },
    CountryInfo { code: "SY", name: "SY", bancho_id: 204, flag: "🌐" },
    CountryInfo { code: "SZ", name: "SZ", bancho_id: 205, flag: "🌐" },
    CountryInfo { code: "TC", name: "TC", bancho_id: 206, flag: "🌐" },
    CountryInfo { code: "TD", name: "TD", bancho_id: 207, flag: "🌐" },
    CountryInfo { code: "TF", name: "TF", bancho_id: 208, flag: "🌐" },
    CountryInfo { code: "TG", name: "TG", bancho_id: 209, flag: "🌐" },
    CountryInfo { code: "TH", name: "Thailand", bancho_id: 210, flag: "🇹🇭" },
    CountryInfo { code: "TJ", name: "TJ", bancho_id: 211, flag: "🌐" },
    CountryInfo { code: "TK", name: "TK", bancho_id: 212, flag: "🌐" },
    CountryInfo { code: "TM", name: "TM", bancho_id: 213, flag: "🌐" },
    CountryInfo { code: "TN", name: "TN", bancho_id: 214, flag: "🌐" },
    CountryInfo { code: "TO", name: "TO", bancho_id: 215, flag: "🌐" },
    CountryInfo { code: "TL", name: "TL", bancho_id: 216, flag: "🌐" },
    CountryInfo { code: "TR", name: "TR", bancho_id: 217, flag: "🌐" },
    CountryInfo { code: "TT", name: "TT", bancho_id: 218, flag: "🌐" },
    CountryInfo { code: "TV", name: "TV", bancho_id: 219, flag: "🌐" },
    CountryInfo { code: "TW", name: "Taiwan", bancho_id: 220, flag: "🇹🇼" },
    CountryInfo { code: "TZ", name: "TZ", bancho_id: 221, flag: "🌐" },
    CountryInfo { code: "UA", name: "UA", bancho_id: 222, flag: "🌐" },
    CountryInfo { code: "UG", name: "UG", bancho_id: 223, flag: "🌐" },
    CountryInfo { code: "UM", name: "UM", bancho_id: 224, flag: "🌐" },
    CountryInfo { code: "US", name: "United States", bancho_id: 225, flag: "🇺🇸" },
    CountryInfo { code: "UY", name: "UY", bancho_id: 226, flag: "🌐" },
    CountryInfo { code: "UZ", name: "UZ", bancho_id: 227, flag: "🌐" },
    CountryInfo { code: "VA", name: "VA", bancho_id: 228, flag: "🌐" },
    CountryInfo { code: "VC", name: "VC", bancho_id: 229, flag: "🌐" },
    CountryInfo { code: "VE", name: "VE", bancho_id: 230, flag: "🌐" },
    CountryInfo { code: "VG", name: "VG", bancho_id: 231, flag: "🌐" },
    CountryInfo { code: "VI", name: "VI", bancho_id: 232, flag: "🌐" },
    CountryInfo { code: "VN", name: "Vietnam", bancho_id: 233, flag: "🇻🇳" },
    CountryInfo { code: "VU", name: "VU", bancho_id: 234, flag: "🌐" },
    CountryInfo { code: "WF", name: "Wallis and Futuna", bancho_id: 235, flag: "🇼🇫" },
    CountryInfo { code: "WS", name: "WS", bancho_id: 236, flag: "🌐" },
    CountryInfo { code: "YE", name: "YE", bancho_id: 237, flag: "🌐" },
    CountryInfo { code: "YT", name: "YT", bancho_id: 238, flag: "🌐" },
    CountryInfo { code: "RS", name: "RS", bancho_id: 239, flag: "🌐" },
    CountryInfo { code: "ZA", name: "ZA", bancho_id: 240, flag: "🌐" },
    CountryInfo { code: "ZM", name: "ZM", bancho_id: 241, flag: "🌐" },
    CountryInfo { code: "ME", name: "ME", bancho_id: 242, flag: "🌐" },
    CountryInfo { code: "ZW", name: "ZW", bancho_id: 243, flag: "🌐" },
    CountryInfo { code: "XX", name: "Unknown", bancho_id: 244, flag: "🌐" },
    CountryInfo { code: "A2", name: "A2", bancho_id: 245, flag: "🌐" },
    CountryInfo { code: "O1", name: "O1", bancho_id: 246, flag: "🌐" },
    CountryInfo { code: "AX", name: "AX", bancho_id: 247, flag: "🌐" },
    CountryInfo { code: "GG", name: "GG", bancho_id: 248, flag: "🌐" },
    CountryInfo { code: "IM", name: "IM", bancho_id: 249, flag: "🌐" },
    CountryInfo { code: "JE", name: "JE", bancho_id: 250, flag: "🌐" },
    CountryInfo { code: "BL", name: "BL", bancho_id: 251, flag: "🌐" },
    CountryInfo { code: "MF", name: "MF", bancho_id: 252, flag: "🌐" },
];

pub fn iso_to_bancho_id(iso: &str) -> u8 {
    let upper = iso.trim().to_uppercase();
    COUNTRIES
        .iter()
        .find(|c| c.code == upper)
        .map(|c| c.bancho_id)
        .unwrap_or(233) // default Vietnam (233)
}

pub fn bancho_id_to_iso(id: u8) -> &'static str {
    COUNTRIES
        .iter()
        .find(|c| c.bancho_id == id)
        .map(|c| c.code)
        .unwrap_or("VN")
}

pub fn bancho_id_to_country(id: u8) -> &'static CountryInfo {
    COUNTRIES
        .iter()
        .find(|c| c.bancho_id == id)
        .unwrap_or(&DEFAULT_COUNTRY_INFO)
}
